/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as TrackRouteImport } from './routes/track'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RateRouteImport } from './routes/rate'
import { Route as PaymentRouteImport } from './routes/payment'
import { Route as ParentSpaceRouteImport } from './routes/parent-space'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DeliveryRouteImport } from './routes/delivery'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConfirmationRouteImport } from './routes/confirmation'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as ChildrenRouteImport } from './routes/children'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CatalogueRouteImport } from './routes/catalogue'
import { Route as CartRouteImport } from './routes/cart'
import { Route as BookRouteImport } from './routes/book'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RateRoute = RateRouteImport.update({
  id: '/rate',
  path: '/rate',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentRoute = PaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentSpaceRoute = ParentSpaceRouteImport.update({
  id: '/parent-space',
  path: '/parent-space',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryRoute = DeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmationRoute = ConfirmationRouteImport.update({
  id: '/confirmation',
  path: '/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const ChildrenRoute = ChildrenRouteImport.update({
  id: '/children',
  path: '/children',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogueRoute = CatalogueRouteImport.update({
  id: '/catalogue',
  path: '/catalogue',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/cart': typeof CartRoute
  '/catalogue': typeof CatalogueRoute
  '/chat': typeof ChatRoute
  '/children': typeof ChildrenRoute
  '/community': typeof CommunityRoute
  '/confirmation': typeof ConfirmationRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/delivery': typeof DeliveryRoute
  '/faq': typeof FaqRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/parent-space': typeof ParentSpaceRoute
  '/payment': typeof PaymentRoute
  '/rate': typeof RateRoute
  '/signup': typeof SignupRoute
  '/track': typeof TrackRoute
  '/wishlist': typeof WishlistRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/cart': typeof CartRoute
  '/catalogue': typeof CatalogueRoute
  '/chat': typeof ChatRoute
  '/children': typeof ChildrenRoute
  '/community': typeof CommunityRoute
  '/confirmation': typeof ConfirmationRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/delivery': typeof DeliveryRoute
  '/faq': typeof FaqRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/parent-space': typeof ParentSpaceRoute
  '/payment': typeof PaymentRoute
  '/rate': typeof RateRoute
  '/signup': typeof SignupRoute
  '/track': typeof TrackRoute
  '/wishlist': typeof WishlistRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/book': typeof BookRoute
  '/cart': typeof CartRoute
  '/catalogue': typeof CatalogueRoute
  '/chat': typeof ChatRoute
  '/children': typeof ChildrenRoute
  '/community': typeof CommunityRoute
  '/confirmation': typeof ConfirmationRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/delivery': typeof DeliveryRoute
  '/faq': typeof FaqRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/orders': typeof OrdersRoute
  '/parent-space': typeof ParentSpaceRoute
  '/payment': typeof PaymentRoute
  '/rate': typeof RateRoute
  '/signup': typeof SignupRoute
  '/track': typeof TrackRoute
  '/wishlist': typeof WishlistRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/book'
    | '/cart'
    | '/catalogue'
    | '/chat'
    | '/children'
    | '/community'
    | '/confirmation'
    | '/contact'
    | '/dashboard'
    | '/delivery'
    | '/faq'
    | '/home'
    | '/login'
    | '/orders'
    | '/parent-space'
    | '/payment'
    | '/rate'
    | '/signup'
    | '/track'
    | '/wishlist'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/book'
    | '/cart'
    | '/catalogue'
    | '/chat'
    | '/children'
    | '/community'
    | '/confirmation'
    | '/contact'
    | '/dashboard'
    | '/delivery'
    | '/faq'
    | '/home'
    | '/login'
    | '/orders'
    | '/parent-space'
    | '/payment'
    | '/rate'
    | '/signup'
    | '/track'
    | '/wishlist'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/book'
    | '/cart'
    | '/catalogue'
    | '/chat'
    | '/children'
    | '/community'
    | '/confirmation'
    | '/contact'
    | '/dashboard'
    | '/delivery'
    | '/faq'
    | '/home'
    | '/login'
    | '/orders'
    | '/parent-space'
    | '/payment'
    | '/rate'
    | '/signup'
    | '/track'
    | '/wishlist'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BookRoute: typeof BookRoute
  CartRoute: typeof CartRoute
  CatalogueRoute: typeof CatalogueRoute
  ChatRoute: typeof ChatRoute
  ChildrenRoute: typeof ChildrenRoute
  CommunityRoute: typeof CommunityRoute
  ConfirmationRoute: typeof ConfirmationRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  DeliveryRoute: typeof DeliveryRoute
  FaqRoute: typeof FaqRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  OrdersRoute: typeof OrdersRoute
  ParentSpaceRoute: typeof ParentSpaceRoute
  PaymentRoute: typeof PaymentRoute
  RateRoute: typeof RateRoute
  SignupRoute: typeof SignupRoute
  TrackRoute: typeof TrackRoute
  WishlistRoute: typeof WishlistRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rate': {
      id: '/rate'
      path: '/rate'
      fullPath: '/rate'
      preLoaderRoute: typeof RateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment': {
      id: '/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof PaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent-space': {
      id: '/parent-space'
      path: '/parent-space'
      fullPath: '/parent-space'
      preLoaderRoute: typeof ParentSpaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery': {
      id: '/delivery'
      path: '/delivery'
      fullPath: '/delivery'
      preLoaderRoute: typeof DeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmation': {
      id: '/confirmation'
      path: '/confirmation'
      fullPath: '/confirmation'
      preLoaderRoute: typeof ConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/children': {
      id: '/children'
      path: '/children'
      fullPath: '/children'
      preLoaderRoute: typeof ChildrenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogue': {
      id: '/catalogue'
      path: '/catalogue'
      fullPath: '/catalogue'
      preLoaderRoute: typeof CatalogueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BookRoute: BookRoute,
  CartRoute: CartRoute,
  CatalogueRoute: CatalogueRoute,
  ChatRoute: ChatRoute,
  ChildrenRoute: ChildrenRoute,
  CommunityRoute: CommunityRoute,
  ConfirmationRoute: ConfirmationRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  DeliveryRoute: DeliveryRoute,
  FaqRoute: FaqRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  OrdersRoute: OrdersRoute,
  ParentSpaceRoute: ParentSpaceRoute,
  PaymentRoute: PaymentRoute,
  RateRoute: RateRoute,
  SignupRoute: SignupRoute,
  TrackRoute: TrackRoute,
  WishlistRoute: WishlistRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
